### ISSUE TITLE
Problem with 'output'

### ISSUE THREAD

**Issue by no-e-in** [Gagravarr/PDFtkBox#1]
java -jar PDFtkBox.jar -import old.pdf -bookmarks book.txt output new.pdf  --> output
java -jar PDFtkBox.jar -import old.pdf -bookmarks book.txt new.pdf  --> new.pdf [ok]

**Comment by no-e-in** [comment]
From Readme.md:
>To import the bookmarks, from a text file, saving as a new file, use one of:
java -jar PDFtkBox.jar -import <input.pdf> -bookmarks <bookmarks.txt> output <output.pdf>

**Comment by Gagravarr** [comment]
Sorry, there was a copy-and-paste error in one section of the docs. Fixed as of 54e0934, you can now do either
`java -jar PDFtkBox.jar -import old.pdf -bookmarks book.txt new.pdf `
or
`java -jar PDFtkBox.jar -import old.pdf -bookmarks book.txt -output new.pdf `
Note that you need a Java-style `-output` if you're going to do that, the PDFBox style plain `output` isn't supported when doing java-style `-import`
